export interface ReleaseNote {
  version: string;
  date: string;
  title: string;
  highlights: string[];
  details?: string;
  badge?: "new" | "fix" | "improvement";
}

export const APP_VERSION = "1.14.1";

export const RELEASE_NOTES: ReleaseNote[] = [
  {
    version: "1.14.1",
    date: "2026-03-24",
    title: "Guardrail Fixes, Team Install Email & UI Gates",
    highlights: [
      "Send Install Email — new button on Team page lets admins email members a link to install the browser extension (individual or bulk)",
      "Smart pattern detection fix — all smart detection rules (phone, DOB, IP, internal domains, file paths, etc.) now fire correctly when enabled in org settings",
      "CVV pattern fix — now detects natural phrasing like 'The CVV is 742' in addition to 'CVV: 742'",
      "International phone number pattern fix — correctly detects numbers like +442071234567",
      "Import/Export button — now visible on all plans (Free plan users are directed to upgrade page)",
      "Member billing gates — members can now navigate to Billing and Plan & Usage tabs where they see 'Contact admin' messaging instead of hidden tabs",
    ],
    badge: "fix",
  },
  {
    version: "1.14.0",
    date: "2026-03-19",
    title: "AI Chat Overhaul, Smart Redaction & File Uploads",
    highlights: [
      "Smart Redaction — new 'Redact' severity option auto-replaces sensitive data with placeholders instead of blocking. API keys become [API_KEYS], emails become [PII]. Message still sends safely.",
      "File upload support in AI Chat — upload PDFs, Word docs, code files, CSVs. Files are scanned by DLP before text is extracted and sent to the AI.",
      "AI Chat UI redesign — clean document-style assistant messages (no bubbles), integrated composer input bar, minimal header, 2x2 suggestion cards",
      "Collections — organize conversations with color-coded labels. Right-click to add, click to filter. Replaces folders and tags.",
      "Favorites — star conversations to pin them to the top. Visible in both Chats and Favorites tabs.",
      "Admin slash commands with real data — /activity, /violations, /usage, /audit query your actual database and inject results as AI context",
      "Multi-model compare — send the same message to two different AI models side-by-side",
      "Right-click context menu on conversations — pin, rename, share, export, collections, delete",
      "ChatGPT-style smart scroll — auto-scrolls during streaming but stops if you scroll up to read",
      "Code blocks with language headers and copy buttons",
      "Response rating (thumbs up/down) on AI messages",
      "Sidebar restructured — Security section (Guardrails, Activity Log, Analytics) now front and center",
      "10 new SEO blog articles on AI DLP, governance, and security",
      "4 conversion-optimized Google Ads landing pages",
      "55 bugs fixed across 2 QA passes",
    ],
    badge: "new",
  },
  {
    version: "1.13.0",
    date: "2026-03-17",
    title: "Slack Integration, MCP Server & Campaign Improvements",
    highlights: [
      "Slack integration — connect your workspace for real-time DLP violation alerts, prompt approval notifications, and weekly activity digests",
      "MCP (Model Context Protocol) server — connect Claude Desktop, Cursor, Windsurf, and other AI coding tools to your prompt library, DLP scanning, and audit logging",
      "MCP API key management with granular scope control, expiry dates, and usage tracking",
      "Campaign duplicate — copy any campaign (draft, scheduled, or sent) with one click",
      "Custom email templates — save any campaign email as a reusable template, browse saved templates in the template picker",
      "Vanilla email templates now render like real personal emails — no gray background, no centering, minimal unsubscribe link",
      "Campaign analytics webhook — receives open, click, bounce, and unsubscribe events from Resend in real-time",
      "Campaign status polling — queued/sending campaigns auto-update to Sent without refreshing",
      "Ticket thread UI — collapsible reply area gives more reading space, timeline connectors between messages, latest message always expanded",
      "Settings reorganized — Integrations now has its own tab, visible in the settings cog dropdown",
      "Add contacts to audience lists with manual entry fields (name, email, company) or bulk paste with format detection",
    ],
    badge: "new",
  },
  {
    version: "1.12.0",
    date: "2026-03-17",
    title: "Realtime Updates, Security Hardening & Admin Improvements",
    highlights: [
      "Realtime updates across all dashboard pages — team members, invites, prompts, and analytics update live without refreshing",
      "Fixed invite signup flow — new members now reliably join the invited org even when the database trigger fails",
      "Stripe billing properly cancelled on all org deletion paths (leave-org, invite accept, domain-join)",
      "Moved team member operations (remove, role change, shield toggle) to server-side API with proper auth checks",
      "Admin views now show realtime data with cross-links — click org names in subscriptions or users to jump to org detail",
      "Added time period selectors to admin analytics and funnel views",
      "Compliance packs visible to all plans with upgrade prompts for free/pro users",
      "Session expiry now redirects to login with clear message instead of silent failure",
      "Campaign editor: new visual WYSIWYG tab and test email send from preview",
      "Setup wizard connector lines fixed, modernized circle design",
      "Import/export now supports drag-and-drop file upload",
      "Fixed MRR calculation to exclude trialing subscriptions",
    ],
    badge: "improvement",
  },
  {
    version: "1.11.0",
    date: "2026-03-13",
    title: "Updated Plan Limits, Save Button & Extension Improvements",
    highlights: [
      "Updated plan limits — Free plans now support up to 3 members, Pro plans up to 12 members",
      "Save button on AI tools — hover over any prompt you sent in ChatGPT, Claude, Gemini, Copilot, or Perplexity to save it directly to your library",
      "Auto-open extension on save — clicking save opens the extension popup with the create form pre-filled",
      "Full-height create prompt form — the form now fills the entire extension window instead of a tiny scrollable area",
      "Persistent guardrails footer — the guardrails status bar now shows on all extension views",
      "Usage cap indicators — admins see member, prompt, and guideline usage vs plan limits on Team, Vault, and Guidelines pages",
      "SEO cross-linking — improved internal linking across marketing pages for better Google indexing",
      "Fixed CSP violations, auth sign-out loop, and duplicate context menu entries in the extension",
    ],
    badge: "new",
  },
  {
    version: "1.10.0",
    date: "2026-03-09",
    title: "19 Compliance Packs, Sortable Tables & Guardrail Insights",
    highlights: [
      "13 new compliance packs — FERPA, GLBA, NIST 800-171, FedRAMP, NAIC, ITAR, CJIS, COPPA, FTC/Retail, HITECH, SOX, RESPA/TILA, and Legal Privilege (19 total across 8 industries)",
      "Browse All Packs modal — explore compliance packs organized by industry category with install status",
      "Sortable guardrail tables — click any column header on Policies or Violations to sort ascending/descending",
      "Pack source tracking & filtering — see which compliance pack each rule came from, filter policies by pack",
      "Smarter guardrail stats — week-over-week violation trends, block rate, top triggered rule, active/inactive policy counts",
      "Dashboard & Analytics guardrail widgets — admins and managers see guardrail activity, top triggered rules, and per-user breakdowns",
      "Manage Teams modal — centralized team management (create, edit, delete) without cluttering filter chips",
      "Fixed org chart team detail — edit and delete now work correctly from within team drill-down views",
    ],
    badge: "new",
  },
  {
    version: "1.9.0",
    date: "2026-03-09",
    title: "Org Chart, Extension Alerts & Team UX Improvements",
    highlights: [
      "Visual org chart — toggle between table and org chart view to see teams, members, and roles at a glance",
      "Extension inactive alerts — admins and managers receive in-app notifications and emails when a member's extension goes inactive for 24+ hours",
      "Prompt grid view — switch between list and tile layout on the Prompts page",
      "Smart invite modal — auto-detects existing members and switches to 'Add to Team' instead of sending a duplicate invite",
      "Pending invites in table — pending invitations now appear inline in the members table with status badges and quick actions",
      "Member source tracking — see which members were manually invited, bulk imported, or synced from Google Workspace",
    ],
    badge: "new",
  },
  {
    version: "1.8.0",
    date: "2026-03-09",
    title: "Team-Scoped Prompts, Role Permissions & Extension Redesign",
    highlights: [
      "AI-powered rule generation — describe what to protect in plain English, AI creates the guardrail patterns",
      "Anthropic (Claude) support — connect your Anthropic API key alongside OpenAI for AI detection and rule generation",
      "Team-scoped prompt visibility — members only see their own prompts and approved prompts from their teams",
      "Guardrail suggestions — team members can suggest new security rules for admin review",
      "Redesigned extension overlay — shield indicator with contextual states (active, inactive, scanning)",
      "Compose email from admin inbox — send emails to any address directly from the ticket system",
    ],
    badge: "new",
  },
  {
    version: "1.7.0",
    date: "2026-02-28",
    title: "Admin Security Controls & Extension Settings",
    highlights: [
      "New Security settings tab — 6 org-level toggles to control extension behavior, guardrails, and activity logging",
      "Disable guardrail overrides — treat all warnings as hard blocks for stricter enforcement",
      "Auto-redact mode — automatically replace sensitive data with {{PLACEHOLDER}} tokens instead of blocking",
      "Activity logging toggle — disable conversation logging while still tracking usage counts",
      "Plan-gated security features with Team+ badges for custom_security and audit_log controls",
    ],
    badge: "new",
  },
  {
    version: "1.6.0",
    date: "2026-02-28",
    title: "Google Workspace Sync, Auto-Join & Bulk Role Management",
    highlights: [
      "Google Workspace directory sync — connect your Google admin, import users, and map groups to teams",
      "Domain-based auto-join — new users with matching email domains automatically join your org",
      "Custom invite welcome message — add a personal note that appears in all invite emails",
      "Bulk role assignment — select multiple members and change their roles at once from the Team page",
    ],
    badge: "new",
  },
  {
    version: "1.5.0",
    date: "2026-02-28",
    title: "Bulk Employee Import & Integrations",
    highlights: [
      "Bulk CSV import — upload or paste a CSV to invite dozens of members at once",
      "Auto-create teams during import when team names don't exist yet",
      "Preview validation before sending: see which rows are valid, which will create new teams, and which will be skipped",
      "New Integrations settings page with Google Workspace, Microsoft Entra ID, and SCIM 2.0 cards",
    ],
    badge: "new",
  },
  {
    version: "1.4.0",
    date: "2026-02-28",
    title: "Two-Factor Auth, Profile & Team Improvements",
    highlights: [
      "Two-factor authentication (TOTP) for admins and managers with org-level enforcement",
      "Avatar upload with drag-and-drop on your profile",
      "Change your email address — admins can update member emails too",
      "Color-coded categories with 12 preset colors",
      "Edit and delete teams from the team detail view",
    ],
    badge: "new",
  },
  {
    version: "1.3.0",
    date: "2026-02-27",
    title: "Compliance Packs, Auto-Sanitization & More",
    highlights: [
      "One-click compliance policy packs (HIPAA, GDPR, PCI-DSS, CCPA, SOC 2, General PII)",
      "Auto-sanitization replaces sensitive data with safe {{PLACEHOLDER}} tokens",
      "Prompt effectiveness analytics with rating distribution",
      "Dedicated approval queue for pending prompts and rule suggestions",
      "Version diff view — compare any two versions side by side",
    ],
    badge: "new",
  },
  {
    version: "1.2.0",
    date: "2026-01-15",
    title: "Template Packs & Import Improvements",
    highlights: [
      "Built-in template packs for common workflows",
      "Improved CSV/JSON import with column mapping",
      "Bulk export with metadata preservation",
      "Template variable default values",
    ],
    badge: "improvement",
  },
  {
    version: "1.1.0",
    date: "2025-12-10",
    title: "Browser Extension & Guardrails",
    highlights: [
      "Chrome extension with side panel support",
      "Real-time DLP scanning on outbound prompts",
      "15 built-in security patterns",
      "Activity logging and audit trail",
    ],
    badge: "new",
  },
  {
    version: "1.0.0",
    date: "2025-11-01",
    title: "Initial Release",
    highlights: [
      "Shared prompt vault with search and tags",
      "Quality guidelines with 14 built-in templates",
      "Team management with Admin, Manager, and Member roles",
      "Analytics dashboard with usage tracking",
    ],
    badge: "new",
  },
];
